### ISSUE TITLE
Prometheus.cl maintenance question

### ISSUE THREAD

**Issue by svetlyak40wt** [deadtrickster/prometheus.cl#4]
Ilia, are you still interested in maintaining Common Lisp libraries?

If not, I wish to take over Prometheus client's maintenance.

**Comment by deadtrickster** [comment]
yes I definitely interested! And of course I don't want to slow people down. Can you throw a couple PRs to make sure we are aligned and I'll add you as maintainer here. Sounds good?

**Comment by svetlyak40wt** [comment]
Great! I'll send the pull requests soon.
